FROM golang:1.16.2-alpine AS builder
RUN mkdir /root/new-leaf/
WORKDIR /root/new-leaf/
COPY main.go .
COPY go.mod .
RUN go get github.com/bwmarrin/discordgo@v0.23.2
RUN go get github.com/TwinProduction/go-away@v1.1.2
RUN go build -o ./build/run

FROM alpine:3.13.2
WORKDIR /root/
COPY --from=builder /root/new-leaf/build/run .

